import stirfry from "@/assets/stirfry.jpg";
import beansToast from "@/assets/beans-toast.jpg";
import lentilCurry from "@/assets/lentil-curry.jpg";
import sausagePasta from "@/assets/sausage-pasta.jpg";
import chilli from "@/assets/chilli.jpg";
import eggFriedRice from "@/assets/egg-fried-rice.jpg";
import fajitas from "@/assets/fajitas.jpg";
import tomatoSoup from "@/assets/tomato-soup.jpg";
import tunaPastaBake from "@/assets/tuna-pasta-bake.jpg";
import jacketPotatoBeans from "@/assets/jacket-potato-beans.jpg";
import veggieChilli from "@/assets/veggie-chilli.jpg";
import carbonara from "@/assets/carbonara.jpg";
import chickpeaCurry from "@/assets/chickpea-curry.jpg";
import shakshuka from "@/assets/shakshuka.jpg";
import sweetPotatoSoup from "@/assets/sweet-potato-soup.jpg";
import chickenRiceTraybake from "@/assets/chicken-rice-traybake.jpg";
import mushroomRisotto from "@/assets/mushroom-risotto.jpg";
import salmonNoodles from "@/assets/salmon-noodles.jpg";
import halloumiWraps from "@/assets/halloumi-wraps.jpg";
import sausageTrayRoast from "@/assets/sausage-tray-roast.jpg";
import dalTarka from "@/assets/dal-tarka.jpg";
import tomatoPasta from "@/assets/tomato-pasta.jpg";
import chickenNoodleSoup from "@/assets/chicken-noodle-soup.jpg";
import veggieBurritos from "@/assets/veggie-burritos.jpg";
import omeletteCheese from "@/assets/omelette-cheese.jpg";
import pestoGnocchi from "@/assets/pesto-gnocchi.jpg";
import beefMinceHash from "@/assets/beef-mince-hash.jpg";
import porridgeBanana from "@/assets/porridge-banana.jpg";

export type Recipe = {
  id: string;
  title: string;
  description: string;
  price: number;
  minutes: number;
  serves: number;
  tags: string[];
  author: string;
  likes: number;
  image: string;
  ingredients: string[];
  steps: string[];
};

export const recipes: Recipe[] = [
  {
    id: "stir-fry",
    title: "5-Minute Student Stir-Fry",
    description:
      "A quick, cheap veggie stir-fry that's ready faster than instant noodles — and way tastier.",
    price: 0.9,
    minutes: 10,
    serves: 2,
    tags: ["quick", "vegetarian", "budget"],
    author: "Jess",
    likes: 12,
    image: stirfry,
    ingredients: [
      "1 tbsp vegetable oil",
      "300g frozen stir-fry vegetable mix",
      "2 garlic cloves, finely chopped",
      "1 tsp grated ginger (or 1/2 tsp ground)",
      "2 nests dried egg noodles (150g)",
      "2 tbsp soy sauce",
      "1 tsp honey or sugar",
      "1 tsp sesame oil (optional)",
    ],
    steps: [
      "Boil the kettle, pour over the noodles in a bowl and leave for 4 minutes, then drain.",
      "Heat the oil in a large frying pan or wok over high heat until shimmering.",
      "Add the frozen vegetables and stir-fry for 3 minutes until hot and starting to colour.",
      "Add the garlic and ginger and cook for 30 seconds, stirring so they don't burn.",
      "Tip in the drained noodles with the soy sauce and honey; toss for 1–2 minutes.",
      "Finish with sesame oil, taste, and add a splash more soy if needed.",
    ],
  },
  {
    id: "beans-toast",
    title: "Baked Beans on Toast with a Twist",
    description: "The classic student meal, upgraded with cheese and a pinch of chilli flakes.",
    price: 0.6,
    minutes: 7,
    serves: 1,
    tags: ["quick", "budget", "vegetarian"],
    author: "Tom",
    likes: 8,
    image: beansToast,
    ingredients: [
      "1 x 400g tin baked beans",
      "2 thick slices of bread",
      "30g cheddar, grated",
      "1 tsp butter",
      "1/4 tsp chilli flakes",
      "1/2 tsp Worcestershire sauce (or a dash of soy)",
      "Black pepper",
    ],
    steps: [
      "Tip the beans into a small pan with the chilli flakes and Worcestershire sauce.",
      "Simmer over medium heat for 4–5 minutes, stirring, until thick and glossy.",
      "Toast the bread and butter it while hot.",
      "Stir half the cheese through the beans until melted.",
      "Spoon the beans over the toast, scatter the rest of the cheese on top and grind over pepper.",
    ],
  },
  {
    id: "lentil-curry",
    title: "One-Pot Lentil Curry",
    description: "Hearty, filling and cheap — makes 4 portions you can freeze for later.",
    price: 1.2,
    minutes: 30,
    serves: 4,
    tags: ["vegetarian", "batch-cook", "budget"],
    author: "Aisha",
    likes: 21,
    image: lentilCurry,
    ingredients: [
      "1 tbsp oil",
      "1 onion, diced",
      "3 garlic cloves, crushed",
      "2 tsp curry powder",
      "1 tsp ground cumin",
      "1/2 tsp turmeric",
      "250g dried red lentils, rinsed",
      "1 x 400g tin chopped tomatoes",
      "1 x 400ml tin coconut milk",
      "500ml vegetable stock",
      "Handful of spinach (optional)",
      "Salt, pepper and a squeeze of lemon",
    ],
    steps: [
      "Heat the oil in a large pan and cook the onion for 5 minutes until soft.",
      "Add the garlic and spices and fry for 1 minute until fragrant.",
      "Stir in the lentils, tomatoes, coconut milk and stock.",
      "Bring to a boil, then simmer uncovered for 20 minutes, stirring now and then, until the lentils collapse.",
      "Stir in the spinach until wilted, then season with salt, pepper and lemon juice.",
      "Serve with rice or flatbread; cool leftovers quickly and freeze in portions.",
    ],
  },
  {
    id: "sausage-pasta",
    title: "Sausage and Tomato Pasta",
    description:
      "A comforting bowl of pasta featuring pork sausages in a rich, tangy tomato sauce.",
    price: 1.2,
    minutes: 20,
    serves: 1,
    tags: ["pasta", "pork", "comforting"],
    author: "Marcus",
    likes: 15,
    image: sausagePasta,
    ingredients: [
      "100g dried pasta (penne or rigatoni)",
      "2 pork sausages",
      "1 tsp oil",
      "1 garlic clove, sliced",
      "1/2 tsp dried oregano",
      "1/2 x 400g tin chopped tomatoes",
      "1 tsp tomato purée",
      "Pinch of sugar",
      "Grated parmesan or cheddar, to serve",
    ],
    steps: [
      "Cook the pasta in well-salted boiling water according to the packet.",
      "Meanwhile squeeze the sausage meat out of its skins into an oiled frying pan in rough chunks.",
      "Fry over medium-high heat for 5 minutes until browned all over.",
      "Add the garlic and oregano, cook 1 minute, then stir in the tomatoes, purée and sugar.",
      "Simmer for 8 minutes, loosening with a splash of pasta water if it gets thick.",
      "Drain the pasta, toss into the sauce, season and top with cheese.",
    ],
  },
  {
    id: "chilli-con-carne",
    title: "Batch-Cook Chilli con Carne",
    description: "A freezer-friendly chilli that gets cheaper — and better — the bigger you make it.",
    price: 1.35,
    minutes: 45,
    serves: 4,
    tags: ["batch-cook", "beef", "budget"],
    author: "Priya",
    likes: 27,
    image: chilli,
    ingredients: [
      "1 tbsp oil",
      "1 onion, diced",
      "1 red pepper, diced",
      "2 garlic cloves, crushed",
      "500g beef mince",
      "2 tsp ground cumin",
      "1 tbsp mild chilli powder",
      "1 tsp smoked paprika",
      "1 x 400g tin chopped tomatoes",
      "1 x 400g tin kidney beans, drained",
      "1 beef stock cube in 200ml water",
      "Rice and soured cream, to serve",
    ],
    steps: [
      "Fry the onion and pepper in the oil for 6–8 minutes until soft.",
      "Add the garlic and spices and cook for 1 minute.",
      "Turn the heat up, add the mince and brown it well, breaking up the lumps.",
      "Pour in the tomatoes, beans and stock and bring to a simmer.",
      "Cook uncovered for 25–30 minutes until thick and rich, stirring occasionally.",
      "Season, then serve over rice with soured cream. Freezes for up to 3 months.",
    ],
  },
  {
    id: "egg-fried-rice",
    title: "Leftover Egg Fried Rice",
    description: "Turn yesterday's rice into dinner in under ten minutes with two eggs and a wok.",
    price: 0.55,
    minutes: 10,
    serves: 2,
    tags: ["quick", "vegetarian", "leftovers"],
    author: "Danny",
    likes: 19,
    image: eggFriedRice,
    ingredients: [
      "400g cold cooked rice (cooked and chilled the day before)",
      "2 eggs, beaten",
      "1 tbsp vegetable oil",
      "100g frozen peas",
      "2 spring onions, sliced",
      "1 garlic clove, finely chopped",
      "1.5 tbsp soy sauce",
      "1/2 tsp sesame oil",
    ],
    steps: [
      "Heat half the oil in a wok over high heat and scramble the eggs for 30 seconds; tip onto a plate.",
      "Add the rest of the oil, then the garlic and white parts of the spring onion; fry 30 seconds.",
      "Add the peas and cold rice, breaking up any clumps, and stir-fry for 3–4 minutes until piping hot.",
      "Return the egg, add the soy sauce and toss everything together for 1 minute.",
      "Finish with sesame oil and the green spring onion tops.",
      "Only use rice that was chilled quickly after cooking, and reheat it until steaming.",
    ],
  },
  {
    id: "chicken-fajitas",
    title: "Sheet-Pan Chicken Fajitas",
    description: "Everything roasts on one tray — minimal washing up, maximum flavour.",
    price: 1.8,
    minutes: 30,
    serves: 3,
    tags: ["chicken", "one-pan", "sharing"],
    author: "Leah",
    likes: 24,
    image: fajitas,
    ingredients: [
      "400g chicken breast or thigh, sliced",
      "2 peppers, sliced",
      "1 red onion, sliced",
      "2 tbsp oil",
      "2 tsp smoked paprika",
      "1 tsp ground cumin",
      "1/2 tsp garlic powder",
      "1/2 tsp dried oregano",
      "Juice of 1 lime",
      "6 tortillas, to serve",
    ],
    steps: [
      "Heat the oven to 220C / 200C fan / gas 7.",
      "Toss the chicken, peppers and onion on a large baking tray with the oil and spices.",
      "Spread out in a single layer — crowding steams the veg instead of charring it.",
      "Roast for 20–22 minutes, tossing halfway, until the chicken is cooked through and the edges catch.",
      "Squeeze over the lime and warm the tortillas in the oven for the last 2 minutes.",
      "Pile into the tortillas with anything else you have: soured cream, cheese, salsa.",
    ],
  },
  {
    id: "tomato-soup",
    title: "Roasted Tomato Soup",
    description: "Six ingredients, one blender, and a soup that tastes nothing like the tin.",
    price: 0.75,
    minutes: 40,
    serves: 4,
    tags: ["vegan", "batch-cook", "budget"],
    author: "Sam",
    likes: 16,
    image: tomatoSoup,
    ingredients: [
      "800g tomatoes, halved (or 2 x 400g tins)",
      "1 onion, cut into wedges",
      "4 garlic cloves, unpeeled",
      "2 tbsp olive oil",
      "500ml vegetable stock",
      "1 tsp sugar",
      "Handful of basil",
      "Salt and black pepper",
    ],
    steps: [
      "Heat the oven to 200C / 180C fan / gas 6.",
      "Toss the tomatoes, onion and garlic with the oil, salt and pepper on a roasting tray.",
      "Roast for 30 minutes until soft and blistered.",
      "Squeeze the garlic out of its skins into a pan with the roasted veg and the stock.",
      "Simmer for 5 minutes, then blend until smooth with the sugar and most of the basil.",
      "Season to taste and serve with the rest of the basil and bread for dunking.",
    ],
  },
  {
    id: "tuna-pasta-bake",
    title: "Tuna Pasta Bake",
    description: "Store-cupboard hero: tinned tuna, sweetcorn and pasta under a cheesy lid.",
    price: 1.1,
    minutes: 35,
    serves: 4,
    tags: ["batch-cook", "budget", "pescatarian"],
    author: "Priya",
    likes: 21,
    image: tunaPastaBake,
    ingredients: [
      "300g pasta (penne or fusilli)",
      "2 x 145g tins tuna in spring water, drained",
      "1 x 195g tin sweetcorn, drained",
      "300ml milk",
      "25g butter",
      "25g plain flour",
      "80g cheddar, grated",
      "1 tsp Dijon mustard",
      "Salt and black pepper",
    ],
    steps: [
      "Heat the oven to 200C / 180C fan. Boil the pasta for 2 minutes less than the packet says, then drain.",
      "Melt the butter in a pan, stir in the flour and cook for 1 minute.",
      "Whisk in the milk a splash at a time until smooth, then simmer until it thickens.",
      "Stir in the mustard and half the cheese, then season well.",
      "Fold through the pasta, tuna and sweetcorn and tip into a baking dish.",
      "Scatter over the rest of the cheese and bake for 18-20 minutes until bubbling.",
    ],
  },
  {
    id: "jacket-potato-beans",
    title: "Loaded Jacket Potato",
    description: "A whole dinner for under a pound — crisp skin, fluffy middle, beans and cheese.",
    price: 0.65,
    minutes: 75,
    serves: 2,
    tags: ["budget", "vegetarian", "batch-cook"],
    author: "Tom",
    likes: 9,
    image: jacketPotatoBeans,
    ingredients: [
      "2 large baking potatoes",
      "1 tsp vegetable oil",
      "1 x 400g tin baked beans",
      "60g cheddar, grated",
      "1 tbsp butter",
      "Salt and black pepper",
    ],
    steps: [
      "Heat the oven to 220C / 200C fan. Prick the potatoes all over with a fork.",
      "Rub with oil and plenty of salt and bake directly on the shelf for 60-70 minutes.",
      "Warm the beans in a small pan for 5 minutes near the end.",
      "Split the potatoes, fluff the insides with a fork and add the butter.",
      "Spoon over the beans, top with cheese and season.",
    ],
  },
  {
    id: "veggie-chilli",
    title: "Three-Bean Veggie Chilli",
    description: "Smoky, freezer-friendly chilli that costs pennies a portion.",
    price: 0.8,
    minutes: 35,
    serves: 4,
    tags: ["vegan", "batch-cook", "budget"],
    author: "Sam",
    likes: 27,
    image: veggieChilli,
    ingredients: [
      "1 tbsp oil",
      "1 onion, diced",
      "2 garlic cloves, chopped",
      "1 red pepper, diced",
      "2 tsp ground cumin",
      "1 tbsp smoked paprika",
      "1 x 400g tin chopped tomatoes",
      "1 x 400g tin kidney beans, drained",
      "1 x 400g tin black beans, drained",
      "1 x 400g tin cannellini beans, drained",
      "200ml vegetable stock",
      "Salt and black pepper",
    ],
    steps: [
      "Soften the onion and pepper in the oil for 8 minutes.",
      "Add the garlic and spices and fry for 1 minute until fragrant.",
      "Tip in the tomatoes, beans and stock and bring to a simmer.",
      "Cook uncovered for 20 minutes, stirring now and then, until thick.",
      "Season generously and serve with rice or a jacket potato.",
    ],
  },
  {
    id: "carbonara",
    title: "Proper Spaghetti Carbonara",
    description: "Four ingredients, no cream, ten minutes. The real thing.",
    price: 1.35,
    minutes: 15,
    serves: 2,
    tags: ["quick", "carnivore"],
    author: "Marco",
    likes: 34,
    image: carbonara,
    ingredients: [
      "200g spaghetti",
      "100g smoked bacon lardons or pancetta",
      "2 large eggs plus 1 yolk",
      "50g parmesan or hard cheese, finely grated",
      "Plenty of black pepper",
    ],
    steps: [
      "Boil the spaghetti in well-salted water.",
      "Fry the bacon in a dry pan over medium heat until the fat renders and it crisps.",
      "Beat the eggs with the cheese and a lot of pepper in a bowl.",
      "Drain the pasta, saving a mugful of the water, and tip it into the bacon pan off the heat.",
      "Pour in the egg mixture and toss quickly, loosening with pasta water until glossy.",
      "Serve at once with more cheese and pepper.",
    ],
  },
  {
    id: "chickpea-curry",
    title: "15-Minute Chickpea Curry",
    description: "Tinned chickpeas, coconut milk and curry powder — dinner before the rice is done.",
    price: 0.85,
    minutes: 15,
    serves: 3,
    tags: ["vegan", "quick", "budget"],
    author: "Aisha",
    likes: 30,
    image: chickpeaCurry,
    ingredients: [
      "1 tbsp oil",
      "1 onion, sliced",
      "2 garlic cloves, chopped",
      "2 tbsp medium curry powder",
      "2 x 400g tins chickpeas, drained",
      "1 x 400ml tin coconut milk",
      "1 tbsp tomato puree",
      "Handful of spinach (optional)",
      "Salt and lemon juice",
    ],
    steps: [
      "Fry the onion in the oil over high heat for 4 minutes.",
      "Add the garlic, curry powder and tomato puree and stir for 1 minute.",
      "Tip in the chickpeas and coconut milk and simmer for 8 minutes.",
      "Stir through the spinach until wilted.",
      "Season with salt and a squeeze of lemon and serve with rice.",
    ],
  },
  {
    id: "shakshuka",
    title: "One-Pan Shakshuka",
    description: "Eggs poached in spiced tomato sauce — brunch, lunch or a lazy dinner.",
    price: 0.95,
    minutes: 25,
    serves: 2,
    tags: ["vegetarian", "quick"],
    author: "Noor",
    likes: 25,
    image: shakshuka,
    ingredients: [
      "1 tbsp olive oil",
      "1 onion, sliced",
      "1 red pepper, sliced",
      "2 garlic cloves, chopped",
      "1 tsp ground cumin",
      "1 tsp smoked paprika",
      "1 x 400g tin chopped tomatoes",
      "4 eggs",
      "Salt, pepper and parsley",
    ],
    steps: [
      "Soften the onion and pepper in the oil for 8 minutes.",
      "Add the garlic and spices, cook 1 minute, then pour in the tomatoes.",
      "Simmer for 8 minutes until thick, then season.",
      "Make four wells and crack in the eggs.",
      "Cover and cook for 5-6 minutes until the whites set but the yolks stay runny.",
      "Scatter with parsley and eat straight from the pan with bread.",
    ],
  },
  {
    id: "sweet-potato-soup",
    title: "Sweet Potato and Coconut Soup",
    description: "Silky, filling and freezes brilliantly in old takeaway tubs.",
    price: 0.7,
    minutes: 35,
    serves: 4,
    tags: ["vegan", "batch-cook", "budget"],
    author: "Jess",
    likes: 18,
    image: sweetPotatoSoup,
    ingredients: [
      "1 tbsp oil",
      "1 onion, chopped",
      "700g sweet potatoes, peeled and cubed",
      "2 garlic cloves",
      "1 tsp ground ginger",
      "700ml vegetable stock",
      "200ml coconut milk",
      "Salt and black pepper",
    ],
    steps: [
      "Fry the onion in the oil for 5 minutes until soft.",
      "Add the garlic and ginger for 1 minute, then the sweet potato and stock.",
      "Simmer for 20 minutes until the potato collapses when pressed.",
      "Blend until smooth, stir in the coconut milk and warm through.",
      "Season well and serve.",
    ],
  },
  {
    id: "chicken-rice-traybake",
    title: "Chicken and Rice Traybake",
    description: "Everything cooks in one tray, including the rice. Almost no washing up.",
    price: 1.4,
    minutes: 50,
    serves: 4,
    tags: ["carnivore", "batch-cook"],
    author: "Dan",
    likes: 22,
    image: chickenRiceTraybake,
    ingredients: [
      "8 chicken thighs, bone-in",
      "300g long grain rice",
      "1 onion, sliced",
      "2 tsp smoked paprika",
      "1 tsp dried oregano",
      "700ml hot chicken stock",
      "1 tbsp oil",
      "Salt and black pepper",
    ],
    steps: [
      "Heat the oven to 200C / 180C fan.",
      "Rub the chicken with oil, paprika, oregano, salt and pepper.",
      "Scatter the rice and onion in a deep roasting tray and pour over the hot stock.",
      "Sit the chicken on top, skin up, and cover tightly with foil.",
      "Bake for 30 minutes, then uncover and bake 15-20 minutes more until the skin crisps and the rice is tender.",
    ],
  },
  {
    id: "mushroom-risotto",
    title: "Easy Mushroom Risotto",
    description: "Creamy without cream — just stir, sip your tea, stir again.",
    price: 1.05,
    minutes: 35,
    serves: 3,
    tags: ["vegetarian", "batch-cook"],
    author: "Marco",
    likes: 19,
    image: mushroomRisotto,
    ingredients: [
      "1 tbsp olive oil",
      "25g butter",
      "1 onion, finely chopped",
      "250g mushrooms, sliced",
      "250g risotto rice",
      "1 litre hot vegetable stock",
      "40g hard cheese, grated",
      "Salt and black pepper",
    ],
    steps: [
      "Fry the mushrooms in the oil over high heat until browned, then set aside.",
      "Soften the onion in the butter for 6 minutes.",
      "Stir in the rice for 1 minute until glossy.",
      "Add the stock a ladle at a time, stirring, waiting until each is absorbed — about 20 minutes.",
      "Fold the mushrooms and cheese back in, season, and rest for 2 minutes before serving.",
    ],
  },
  {
    id: "salmon-noodles",
    title: "Soy Salmon Noodle Bowl",
    description: "A payday treat that still lands under two pounds a portion.",
    price: 1.95,
    minutes: 20,
    serves: 2,
    tags: ["pescatarian", "quick"],
    author: "Priya",
    likes: 24,
    image: salmonNoodles,
    ingredients: [
      "2 salmon fillets",
      "2 tbsp soy sauce",
      "1 tsp honey",
      "2 nests egg noodles",
      "200g tenderstem broccoli or green beans",
      "1 tsp sesame oil",
      "1 garlic clove, grated",
    ],
    steps: [
      "Heat the oven to 200C / 180C fan. Mix the soy, honey and garlic.",
      "Sit the salmon on a lined tray, spoon over half the glaze and bake for 12-14 minutes.",
      "Boil the noodles and greens together for 4 minutes, then drain.",
      "Toss the noodles with the rest of the glaze and the sesame oil.",
      "Top with the salmon and any tray juices.",
    ],
  },
  {
    id: "halloumi-wraps",
    title: "Crispy Halloumi Wraps",
    description: "Squeaky halloumi, garlic yoghurt and salad in a warm wrap.",
    price: 1.25,
    minutes: 15,
    serves: 2,
    tags: ["vegetarian", "quick"],
    author: "Noor",
    likes: 26,
    image: halloumiWraps,
    ingredients: [
      "225g halloumi, sliced",
      "4 tortilla wraps",
      "4 tbsp natural yoghurt",
      "1 garlic clove, crushed",
      "1/2 cucumber, sliced",
      "1 tomato, sliced",
      "1 tsp oil",
      "Squeeze of lemon",
    ],
    steps: [
      "Fry the halloumi in the oil over medium-high heat for 2 minutes a side until golden.",
      "Mix the yoghurt with the garlic, lemon and a pinch of salt.",
      "Warm the wraps in the dry pan for 20 seconds each.",
      "Spread with the yoghurt, add the salad and halloumi, and roll tightly.",
    ],
  },
  {
    id: "sausage-tray-roast",
    title: "Sausage and Root Veg Roast",
    description: "Chuck it all in a tray, come back in 40 minutes to dinner.",
    price: 1.15,
    minutes: 45,
    serves: 4,
    tags: ["carnivore", "batch-cook", "budget"],
    author: "Dan",
    likes: 17,
    image: sausageTrayRoast,
    ingredients: [
      "8 pork sausages",
      "600g potatoes, cut into chunks",
      "2 carrots, cut into batons",
      "1 red onion, cut into wedges",
      "2 tbsp oil",
      "1 tsp dried rosemary",
      "Salt and black pepper",
    ],
    steps: [
      "Heat the oven to 200C / 180C fan.",
      "Toss the veg with the oil, rosemary, salt and pepper in a large tray.",
      "Roast for 20 minutes, then nestle in the sausages.",
      "Roast another 20-25 minutes, turning once, until everything is browned.",
    ],
  },
  {
    id: "dal-tarka",
    title: "Red Lentil Dal Tarka",
    description: "The cheapest filling meal in the app — about 30p a bowl.",
    price: 0.35,
    minutes: 30,
    serves: 4,
    tags: ["vegan", "budget", "batch-cook"],
    author: "Aisha",
    likes: 41,
    image: dalTarka,
    ingredients: [
      "250g red lentils, rinsed",
      "800ml water",
      "1/2 tsp turmeric",
      "2 tbsp oil or ghee",
      "1 tsp cumin seeds",
      "1 onion, sliced",
      "3 garlic cloves, sliced",
      "1 tsp chilli flakes",
      "Salt and lemon juice",
    ],
    steps: [
      "Simmer the lentils with the water and turmeric for 20 minutes, stirring, until soupy.",
      "Meanwhile heat the oil and sizzle the cumin seeds for 20 seconds.",
      "Add the onion and fry until deep golden, then the garlic and chilli for 30 seconds.",
      "Pour the tarka into the lentils, season with salt and lemon, and stir.",
    ],
  },
  {
    id: "tomato-pasta",
    title: "Garlic Tomato Pasta",
    description: "Five ingredients from the cupboard, restaurant-level sauce.",
    price: 0.55,
    minutes: 20,
    serves: 2,
    tags: ["vegan", "budget", "quick"],
    author: "Jess",
    likes: 15,
    image: tomatoPasta,
    ingredients: [
      "200g spaghetti",
      "2 tbsp olive oil",
      "3 garlic cloves, thinly sliced",
      "1 x 400g tin chopped tomatoes",
      "1/2 tsp sugar",
      "Chilli flakes and salt",
    ],
    steps: [
      "Boil the pasta in salted water.",
      "Warm the oil and garlic gently until the garlic just turns pale gold.",
      "Add the tomatoes, sugar, chilli and salt and simmer hard for 10 minutes.",
      "Drain the pasta and toss it through the sauce with a splash of pasta water.",
    ],
  },
  {
    id: "chicken-noodle-soup",
    title: "Ginger Chicken Noodle Soup",
    description: "What to cook when you're skint and coming down with something.",
    price: 1.0,
    minutes: 25,
    serves: 3,
    tags: ["carnivore", "quick"],
    author: "Tom",
    likes: 13,
    image: chickenNoodleSoup,
    ingredients: [
      "2 chicken breasts, sliced",
      "1 litre chicken stock",
      "1 tbsp grated ginger",
      "2 garlic cloves, sliced",
      "2 nests noodles",
      "150g greens, shredded",
      "2 tbsp soy sauce",
      "2 spring onions",
    ],
    steps: [
      "Bring the stock, ginger and garlic to a simmer.",
      "Add the chicken and poach gently for 8 minutes.",
      "Add the noodles and greens and cook 4 minutes more.",
      "Season with soy sauce and top with spring onions.",
    ],
  },
  {
    id: "veggie-burritos",
    title: "Freezer Bean Burritos",
    description: "Batch-make eight, freeze them, microwave one whenever you're starving.",
    price: 0.9,
    minutes: 30,
    serves: 4,
    tags: ["vegan", "batch-cook", "budget"],
    author: "Sam",
    likes: 20,
    image: veggieBurritos,
    ingredients: [
      "8 tortilla wraps",
      "250g rice, cooked",
      "2 x 400g tins black beans, drained",
      "1 onion, diced",
      "2 tsp ground cumin",
      "1 tsp smoked paprika",
      "1 x 400g tin chopped tomatoes",
      "1 tbsp oil",
      "Salt and pepper",
    ],
    steps: [
      "Fry the onion in the oil for 6 minutes, then add the spices.",
      "Add the beans and tomatoes and simmer for 10 minutes until thick, mashing some beans.",
      "Season, then spoon the mix and rice into the wraps.",
      "Fold in the sides and roll tightly. Eat now, or wrap in foil and freeze.",
    ],
  },
  {
    id: "omelette-cheese",
    title: "Cheese and Herb Omelette",
    description: "Three eggs, three minutes, and a proper meal for about 60p.",
    price: 0.6,
    minutes: 8,
    serves: 1,
    tags: ["vegetarian", "quick", "budget"],
    author: "Marco",
    likes: 11,
    image: omeletteCheese,
    ingredients: [
      "3 eggs",
      "1 tsp butter",
      "30g cheddar, grated",
      "1 tbsp chopped parsley or chives",
      "Salt and black pepper",
    ],
    steps: [
      "Beat the eggs with salt and pepper until completely smooth.",
      "Melt the butter in a small non-stick pan over medium heat.",
      "Pour in the eggs and stir with a spatula for 30 seconds, then leave to set.",
      "Scatter over the cheese and herbs, fold in half and slide onto a plate.",
    ],
  },
  {
    id: "pesto-gnocchi",
    title: "Crispy Pesto Gnocchi",
    description: "Pan-fried gnocchi goes golden and chewy — nothing like the boiled version.",
    price: 1.2,
    minutes: 15,
    serves: 2,
    tags: ["vegetarian", "quick"],
    author: "Priya",
    likes: 28,
    image: pestoGnocchi,
    ingredients: [
      "500g pack fresh gnocchi",
      "2 tbsp olive oil",
      "3 tbsp green pesto",
      "150g cherry tomatoes, halved",
      "Handful of spinach",
      "Grated hard cheese to finish",
    ],
    steps: [
      "Heat the oil in a large frying pan and add the gnocchi straight from the pack.",
      "Fry for 6-8 minutes without stirring too often, until crisp and golden.",
      "Add the tomatoes and cook 2 minutes until they slump.",
      "Off the heat, stir through the pesto and spinach until wilted, then top with cheese.",
    ],
  },
  {
    id: "beef-mince-hash",
    title: "Beef and Potato Hash",
    description: "Leftover potatoes plus mince equals the best kind of fry-up dinner.",
    price: 1.3,
    minutes: 30,
    serves: 3,
    tags: ["carnivore", "budget"],
    author: "Dan",
    likes: 14,
    image: beefMinceHash,
    ingredients: [
      "400g beef mince",
      "500g potatoes, diced small",
      "1 onion, diced",
      "1 tbsp oil",
      "1 tbsp Worcestershire sauce",
      "1 tsp smoked paprika",
      "3 eggs (optional)",
      "Salt and pepper",
    ],
    steps: [
      "Parboil the potatoes for 6 minutes and drain well.",
      "Brown the mince in a large pan over high heat, then set aside.",
      "Fry the potatoes and onion in the oil for 12 minutes until crisp at the edges.",
      "Return the mince with the Worcestershire sauce and paprika, season, and cook 3 minutes.",
      "Fry the eggs and set them on top if you like.",
    ],
  },
  {
    id: "porridge-banana",
    title: "Banana and Peanut Butter Porridge",
    description: "Breakfast for 25p that actually keeps you going until lunch.",
    price: 0.25,
    minutes: 6,
    serves: 1,
    tags: ["vegetarian", "budget", "quick"],
    author: "Jess",
    likes: 10,
    image: porridgeBanana,
    ingredients: [
      "50g porridge oats",
      "250ml milk or water",
      "1 banana, sliced",
      "1 tbsp peanut butter",
      "Pinch of salt",
      "Drizzle of honey (optional)",
    ],
    steps: [
      "Put the oats, liquid and salt in a pan over medium heat.",
      "Stir for 4-5 minutes until thick and creamy.",
      "Stir in the peanut butter until it melts through.",
      "Top with the banana and a drizzle of honey.",
    ],
  },
];

export function getRecipe(id: string) {
  return recipes.find((r) => r.id === id);
}
