/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FridgeRouteImport } from './routes/fridge'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as RecipeIdRouteImport } from './routes/recipe.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FridgeRoute = FridgeRouteImport.update({
  id: '/fridge',
  path: '/fridge',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIdRoute = RecipeIdRouteImport.update({
  id: '/recipe/$id',
  path: '/recipe/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/calendar': typeof CalendarRoute
  '/discover': typeof DiscoverRoute
  '/fridge': typeof FridgeRoute
  '/onboarding': typeof OnboardingRoute
  '/people': typeof PeopleRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/recipe/$id': typeof RecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/calendar': typeof CalendarRoute
  '/discover': typeof DiscoverRoute
  '/fridge': typeof FridgeRoute
  '/onboarding': typeof OnboardingRoute
  '/people': typeof PeopleRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/recipe/$id': typeof RecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/calendar': typeof CalendarRoute
  '/discover': typeof DiscoverRoute
  '/fridge': typeof FridgeRoute
  '/onboarding': typeof OnboardingRoute
  '/people': typeof PeopleRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/recipe/$id': typeof RecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/budget'
    | '/calendar'
    | '/discover'
    | '/fridge'
    | '/onboarding'
    | '/people'
    | '/saved'
    | '/settings'
    | '/setup'
    | '/share'
    | '/profile/$userId'
    | '/recipe/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/budget'
    | '/calendar'
    | '/discover'
    | '/fridge'
    | '/onboarding'
    | '/people'
    | '/saved'
    | '/settings'
    | '/setup'
    | '/share'
    | '/profile/$userId'
    | '/recipe/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/budget'
    | '/calendar'
    | '/discover'
    | '/fridge'
    | '/onboarding'
    | '/people'
    | '/saved'
    | '/settings'
    | '/setup'
    | '/share'
    | '/profile/$userId'
    | '/recipe/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BudgetRoute: typeof BudgetRoute
  CalendarRoute: typeof CalendarRoute
  DiscoverRoute: typeof DiscoverRoute
  FridgeRoute: typeof FridgeRoute
  OnboardingRoute: typeof OnboardingRoute
  PeopleRoute: typeof PeopleRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ShareRoute: typeof ShareRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  RecipeIdRoute: typeof RecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fridge': {
      id: '/fridge'
      path: '/fridge'
      fullPath: '/fridge'
      preLoaderRoute: typeof FridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$id': {
      id: '/recipe/$id'
      path: '/recipe/$id'
      fullPath: '/recipe/$id'
      preLoaderRoute: typeof RecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BudgetRoute: BudgetRoute,
  CalendarRoute: CalendarRoute,
  DiscoverRoute: DiscoverRoute,
  FridgeRoute: FridgeRoute,
  OnboardingRoute: OnboardingRoute,
  PeopleRoute: PeopleRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ShareRoute: ShareRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  RecipeIdRoute: RecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
